augmentation:
  train:
    augs:
      - class_name: albumentations.RandomBrightnessContrast
        params:
          p: 0.3
      - class_name: albumentations.GaussianBlur
        params:
          blur_limit: !!python/tuple [3,5]
          p: 0.3

  val: