
training:
  use_coco: True
  only_detect: True
  num_classes: 43
  epochs: 2

optimizer:
  name: SGD
  params:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005

lr_scheduler:
  name: StepLR
  params:
    step_size: 30
    gamma: 0.1

classifier:


dataset:
  name: GTSDB
  mtsd_labels: C:\Users\saibo\Documents\bachelor_project\data\classes\map_gtsdb2num.json
  num_workers: 4
  threshold: 900
  keep_other: False
  train:
    batch_size: 4
    transforms:
      min_area: 0
      img_size: 1000
  val:
    batch_size: 2
    transforms:
      min_area: 0
      img_size: 
  test:

utils:
  log_dir: logs
  model_dir: saved_models

checkpoint:
  resume: False
  path: 


