testing:
  only_detect: False
  num_classes: 54

dataset:
  name: GTSDB
  num_workers: 4
  mtsd_labels: C:\Users\saibo\Documents\bachelor_project\data\classes\map_gtsdb2num.json
  test:
    batch_size: 16
    transforms:
      min_area: 0
      img_size: 


model_dir: C:\Users\saibo\Documents\bachelor_project\outputs\2022-04-11\21-17-47\saved_models\model.pkl

