datamodule:
  train:
    dir: ${oc.env:DATA}/MTSD/images/train
    batch_size: 1
    num_workers: 0
    pin_memory:
    transforms: true
  val:
    dir: ${oc.env:DATA}/MTSD/images/val
    batch_size: 1
    num_workers: 0
    pin_memory:
    transforms: false
  test:
  anno_dir: ${oc.env:DATA}/MTSD/annotations
  classes_path: ${oc.env:DATA}/classes/reduced_146.json
  include_negative_examples: false

training:
  debug: true
