datamodule:
  train:
    dir: data/MTSD/images/train
    batch_size: 1
    num_workers: 0
    pin_memory:
    transforms: true
  val:
    dir: data/MTSD/images/val
    batch_size: 1
    num_workers: 0
    pin_memory:
    transforms: false
  test:
  anno_dir: data/MTSD/annotations
  classes_path: data/classes/reduced_146.json
  include_negative_examples: false

training:
  debug: true
