_target_: src.datamodules.mtsd_datamodule.MTSDDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 2
train_val_test_split: [55_000, 5_000, 10_000]
num_workers: 4
pin_memory: False
